export class CharacterSkills {
  constructor(
    public level: number = 1,
    public exp: number = 100,
    public hp: number = 100,
    public mana: number = 100,
    public capacity: number = 100,
    public speed: number = 100,
    public strength: number = 10,
    public swordXP: number = 100,
    public axeXP: number = 100,
    public hammerXP: number = 100,
    public shieldingXP: number = 100,
    public accuracy: number = 10,
    public bowXP: number = 100,
    public crossbowXP: number = 100,
    public magic: number = 10,
    public wandXP: number = 100,
    public rodXP: number = 100,
    public woodcuttingXP: number = 100,
    public carpentryXP: number = 100,
    public miningXP: number = 100,
    public blacksmithingXP: number = 100,
    public herbologyXP: number = 100,
    public alchemyXP: number = 100,
    public sorceryXP: number = 100,
    public runeXP: number = 100,
  ) {}
}
