export class CharacterGamePlayInfo {
  constructor(
    public currHealth: number,
    public currMana: number,
    public currCap: number,
    public alchemyExpiring: number,
    public eqMeleeAttack: number = 0,
    public eqMagicAttack: number = 0,
    public eqRangeAttack: number = 0,
    public eqShielding: number = 0,
    public eqDefence: number = 0,
    public eqSpeed: number = 0,
    public extraHP: number = 0,
    public extraMana: number = 0,
    public extraStrength: number = 0,
    public extraAccuracy: number = 0,
    public extraMagic: number = 0,
    public extraSwordSkill: number = 0,
    public extraAxeSkill: number = 0,
    public extraHammerSkill: number = 0,
    public extraShieldingSkill: number = 0,
    public extraBowSkill: number = 0,
    public extraCrossbowSkill: number = 0,
    public extraWandSkill: number = 0,
    public extraRodSkill: number = 0,
    public extraWoodcuttingSkill: number = 0,
    public extraCarpentrySkill: number = 0,
    public extraMiningSkill: number = 0,
    public extraBlackSmithingSkill: number = 0,
    public extraHerbologySkill: number = 0,
    public extraAlchemySkill: number = 0,
    public extraSorcerySkill: number = 0,
    public extraRuneCraftingSkill: number = 0,
  ) {}
}
