export class Equipment {
  constructor(
    public name: string,
    public type: string,
    public img: string,
    public reqProfession: string,
    public reqLevel: number,
    public reqSkill: string,
    public reqSkillLevel: number,
    public meleeAttack: number,
    public shielding: number,
    public defence: number,
    public rangeAttack: number,
    public magic: number,
    public speed: number,
    public weight: number,
    public amount: number = 1,
    public condition: number = 100,
    public rarity: number = 0,
    public extraHP: number = 0,
    public extraMana: number = 0,
    public extraStrength: number = 0,
    public extraAccuracy: number = 0,
    public extraMagic: number = 0,
    public extraSwordSkill: number = 0,
    public extraAxeSkill: number = 0,
    public extraHammerSkill: number = 0,
    public extraShieldingSkill: number = 0,
    public extraBowSkill: number = 0,
    public extraCrossbowSkill: number = 0,
    public extraWandSkill: number = 0,
    public extraRodSkill: number = 0,
    public extraWoodcuttingSkill: number = 0,
    public extraCarpentrySkill: number = 0,
    public extraMiningSkill: number = 0,
    public extraBlackSmithingSkill: number = 0,
    public extraHerbologySkill: number = 0,
    public extraAlchemySkill: number = 0,
    public extraSorcerySkill: number = 0,
    public extraRuneCraftingSkill: number = 0,
    public desc: string = null,
    public usable: boolean = false,
    public stackable: boolean = false,
    public runeElement: string = null,
    public isTwoHanded: boolean = false,
    public sellValue: number = 0,
    public buyValue: number = 0,
  ) {}
}
